version: '3.8'

services:
  localstack:
    container_name: "aws"
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake_key_id
      - AWS_SECRET_ACCESS_KEY=fake_access_key
      - SERVICES=sns,sqs
      - DEBUG=0
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  pixel-service:
    container_name: "pixel-service"
    build:
      context: /src
      dockerfile: ./PixelService/Dockerfile
    ports:
      - "6080:8080"
      - "6081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake_key_id
      - AWS_SECRET_ACCESS_KEY=fake_access_key
      - AWS_ENDPOINT_URL=http://aws:4566
    depends_on:
      - localstack

  storage-service:
    container_name: "storage-service"
    build:
      context: /src
      dockerfile: ./StorageService/Dockerfile
    ports:
      - "7080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake_key_id
      - AWS_SECRET_ACCESS_KEY=fake_access_key
      - AWS_ENDPOINT_URL=http://aws:4566
    depends_on:
      - localstack
      - pixel-service

volumes:
    localstack: